site_name: SigProfilerExtractor
repo_name: SigProfilerSuite/SigProfilerExtractor
repo_url: https://github.com/SigProfilerSuite/SigProfilerExtractor

docs_dir: docs

theme:
  name: readthedocs

nav:
  - Home: home.md
  - '1. Installation': '1. Installation.md'
  - '2. Quick Start Example': '2. Quick Start Example.md'
  - '3. Using the Tool - Input': '3. Using the Tool - Input.md'
  - '4. Using the Tool - Output': '4. Using the Tool - Output.md'
  - '5. Output - All Solutions': '5. Output - All Solutions.md'
  - '6. Output - Suggested Solution': '6. Output - Suggested Solution.md'
