name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Upgrade pip, setuptools, and packaging
      run: |
        python -m pip install --upgrade pip setuptools packaging
    
    - name: Cache src directory
      uses: actions/cache@v4
      with:
        path: ./src/
        key: ${{ runner.os }}-src-grch37
        restore-keys: |
          ${{ runner.os }}-src-
    
    - name: Download GRCh37.tar.gz if not present
      run: |
        if [ ! -f ./src/GRCh37.tar.gz ]; then
          wget --connect-timeout=10 --tries=20 ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/
        fi
    
    - name: Install package
      run: |
        pip install .
    
    - name: Install genome
      run: |
        python install_genome.py ${{ github.workspace }}/src/
    
    - name: Run tests
      run: |
        python3 test.py
    
    - name: Build and push Docker image
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && matrix.python-version == '3.12'
      env:
        GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
        GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
      run: |
        echo "Starting Docker deployment to GHCR for sigprofilersuite..."
        
        VERSION_TAG=$(grep "VERSION = " setup.py | cut -d'"' -f2)
        
        # Get the repository name and convert it to lowercase
        REPO_NAME=$(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/sigprofilersuite/$REPO_NAME"
        
        echo "Building version: $VERSION_TAG for image: $IMAGE_NAME"
        
        echo "$GHCR_PASSWORD" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
        
        docker build \
          --build-arg COMMIT_SHA=${{ github.sha }} \
          -t $IMAGE_NAME:$VERSION_TAG \
          -t $IMAGE_NAME:latest .
        
        docker push $IMAGE_NAME:$VERSION_TAG
        docker push $IMAGE_NAME:latest
        
        echo "Docker deployment to GHCR successful"
